### ISSUE TITLE
Feature request alarm API

### ISSUE THREAD

**Issue by xod442** [HPENetworking/PYHPEIMC#20]
Please add acknowledge and recover apis to alarm.py and get alarm details. Required for Service  Now integration. Address alarm by alarm_id.

**Comment by netmanchris** [comment]
hey @xod442  Ack of request. I'll see if I can get this implemented this week. Once implemented, please provide feedback to let me know the implementation is what you're looking for.  

Thanks for using the library!

@netmanchris

**Comment by netmanchris** [comment]
Hey @xod442 

Implented. Try pyhpeimc-1.0.38   Update using PIP and see if this meets your requirements.

Please confirm if this works so we can close out this issue.

**Comment by xod442** [comment]
OK, works great! I used it to create a new version of snowbridge here. https://github.com/xod442/HPEIMCUtils.git

I issued a new pull request for that as well.

**Comment by netmanchris** [comment]
Awesome! Glad it worked for you. Closing the request.
