### ISSUE TITLE
Issue with getvlans method

### ISSUE THREAD

**Issue by sjordahl** [HPENetworking/PYHPEIMC#24]
There appears to be an issue in the pyhpeimc/plat/vlanm.py file.  I haven't totally dissected the code, but from a quick debug it appears the url variable that's being passed into the method call is either the wrong variable or has been reused.  I added some print statements into the file and found that when I first connect  the method is called correctly, and I printed the following variables that were passed in as parameters:
-  url: http://<ipAddr>:<port>
- get_dev_vlans_url: /imcrs/vlan?devId=28&start=0&size=5000&total=false

After that process is completed, I call dev.getvlans() and get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<user>/.local/lib/python2.7/site-packages/pyhpeimc/objects.py", line 115, in getvlans
    self.vlans = get_dev_vlans(self.devid, self.auth, self.url)
  File "/home/<user>/.local/lib/python2.7/site-packages/pyhpeimc/plat/vlanm.py", line 57, in get_dev_vlans
    f_url = url + get_dev_vlans_url
TypeError: unsupported operand type(s) for +: 'HTTPDigestAuth' and 'str'

This time, the variables passed in as parameters are:
- url: <requests.auth.HTTPDigestAuth object at 0x7fd03fac5150>
- get_dev_vlans_url: /imcrs/vlan?devId=http://<ipAddr>:<port>&start=0&size=5000&total=false

Unless I'm totally off, and this method is only used when a device is first populated, the variable used to populate the url parameter is being reused or a different variable is being passed.

Please advise.

**Comment by netmanchris** [comment]
Hey @sjordahl 

Just got back from vacation.  I'll take a look and see what's going on.  From your detailed comments, I'm thinking you're on the right track. Probably missed this during a recent modification to the class objects.

I'll dig in and try and get this fixed this week.

Chris

**Comment by netmanchris** [comment]
hey @sjordahl 

Looks like you are correct. There was some restructuring of the API done which seems to not have flowed through to the objects functions.  I'll make the adjustments for the getvlans() methods, as well as the addvlan() and delvlan() methods. Caution though, I would not be surprised if there are more bugs floating around in here.  I'm focused on other projects right now so don't have time to dissect the code completely, but if you find something specific, please let me know and I'll do my best to get it fixed ASAP.   Look for library version 1.0.40 with the fixes in it. 

Appreciate you using the library! Let me know if there's anything else I can help with.

**Comment by sjordahl** [comment]
Thanks Chris.  Much appreciated!  I'll give it a whirl when I get a chance.
