### ISSUE TITLE
Looking for information on the Network Traffic Analyzer (NTA) API

### ISSUE THREAD

**Issue by mkernan** [HPENetworking/PYHPEIMC#27]
I have a ticket open with HP asking for documentation on the NTA API, but so far they haven't found anything. They sent me here to post on github as well.

My issue is that I have 200 source devices and it loads all 20,500 interfaces every time I go to add another **single interface**.  This causes me to wait 20 minutes to get the list of all interfaces and then another 20 minutes to filter that list down to all interfaces on a single switch. I can then select the interface I want to monitor and continue on.

Please let me know if there is a solution.

**Comment by netmanchris** [comment]
Hi @mkernan 

Is this a GUI or a API related issue?  Can you tell me which API endpoint you're trying to work with?

thanks

**Comment by mkernan** [comment]
Hi @netmanchris This is a GUI issue. I am hoping to solve it with an API, but I cannot find anything related to NTA in the imcrs/userguide/rest_en/common/index.html. Just wondering if anyone has experience with this and can confirm whether or not the NTA module does have an API.

**Comment by netmanchris** [comment]
Hi Mkernan,

Sorry - There are no NTA specific APIs in the current shipping version ( 7.3 ) of IMC. I would recommend you check with your local partner/account team to get in a feature request in to the product managers.
