### ISSUE TITLE
autoAddDevType and ipSections funtions

### ISSUE THREAD

**Issue by ppenna09** [HPENetworking/PYHPEIMC#5]
In order to use the following functions while creating custom views, please add them to the library.

autoAddDevType
ipSections

Thank you

**Comment by netmanchris** [comment]
hey @ppenna09

Appears to be an issue with the HPEIMC API for this particular post. I added some functions in the device and groups modules to address a workaround for now.  

See https://github.com/HPENetworking/HPEIMCUtils/blob/master/PythonUtilities/Add_Custom_Views/add_devs_to_custom_view.py    a working example.

If you've got support, you may want to open a support case on this to get it fixed. 

@netmanchris
